### ISSUE TITLE
Could not install library through luarocks.

### ISSUE THREAD

**Issue by nagolove** [libmpack/libmpack-lua#23]
I tried `sudo luarocks install nvim-client` command on my linux system and got next error:
```
Installing https://luarocks.org/nvim-client-0.2.2-1.src.rock
Missing dependencies for nvim-client 0.2.2-1:
   mpack (not installed)
   luv (not installed)

nvim-client 0.2.2-1 depends on lua >= 5.1 (5.3-1 provided by VM)
nvim-client 0.2.2-1 depends on mpack (not installed)
Installing https://luarocks.org/mpack-1.0.8-0.rockspec

Error: Failed installing dependency: https://luarocks.org/mpack-1.0.8-0.rockspec - Error fetching file: Failed downloading https://github.com/libmpack/libmpack-lua/releases/download/1.0.8/libmpack-lua-1.0.8.tar.gz - libmpack-lua-1.0.8.tar.gz
```
Such situation with `sudo luarocks install mpack`
```
Installing https://luarocks.org/mpack-1.0.8-0.rockspec

Error: Error fetching file: Failed downloading https://github.com/libmpack/libmpack-lua/releases/download/1.0.8/libmpack-lua-1.0.8.tar.gz - libmpack-lua-1.0.8.tar.gz
```
But I can download source archive manuall by next link `https://github.com/libmpack/libmpack-lua/releases/download/1.0.8/libmpack-lua-1.0.8.tar.gz`

**Comment by teto** [comment]
we've had another similar report: I am not sure luarocks uses the `-L` (follow redirect) flag for GET methods ? uninstalling curl, luarocks picked up wget instead and it worked @hishamhm  ? can you confirm that ? /advice how to configure luarocks to bypass the errors (would  `luarocks config variables.CURL = "curl -L"` be ok)?

**Comment by nagolove** [comment]
> we've had another similar report: I am not sure luarocks uses the `-L` (follow redirect) flag for GET methods ? uninstalling curl, luarocks picked up wget instead and it worked @hishamhm ? can you confirm that ? /advice how to configure luarocks to bypass the errors (would `luarocks config variables.CURL = "curl -L"` be ok)?

As I understood Luarocks adds `-L` flag to curl command line.
https://github.com/luarocks/luarocks/blob/c52a5c57ccffa5a0929593cd94fa5f87e795efd7/src/luarocks/fs/tools.lua#L175

**Comment by teto** [comment]
you can try running in debug mode to see which command is run but when I had looked at the code, I remember one codepath that didn't set the `-L`. Does the error still happen today ? have you tried using wget instead ?

**Comment by nagolove** [comment]
How to enable debug mode? At first I tried to check `use_downloader` function that can use `wget` or `curl`. Futher I searched `fs/lua.lua` sources and found that luarocks trying to call `http_request` for `https` link. But luasec is not installed on my machine. There is no error after installing luasec.

**Comment by teto** [comment]
good job debugging that.
