### ISSUE TITLE
Makefile: Lua C modules shouldn't be linked against liblua

### ISSUE THREAD

**Issue by msva** [libmpack/libmpack-lua#8]
As you can notice [here](https://github.com/libmpack/libmpack-lua/blob/f3c8bf63c189a2ab114c099b5cc24e8083dc4f6a/Makefile#L51), when you compiling the module, you're trying to link the module against liblua, which is wrong behaviour (and adds problems here and there).

Please, read [here](http://lua-users.org/wiki/BuildingModules) (scroll to "Do Not Link Modules to the Lua Core Libraries" paragraph for the reasons).

I was about creating a PR with fix for that issue, but I'd like to do that after PR #7 would be merged (to avoid rebasing after that).

**Comment by tarruda** [comment]
> I was about creating a PR with fix for that issue, but I'd like to do that after PR #7 would be merged (to avoid rebasing after that).

Merged.
