### ISSUE TITLE
lmpack.c: compatibility with lua5.1-no-legacy API

### ISSUE THREAD

**Issue by msva** [libmpack/libmpack-lua#9]
Although, you have some compatibility [logic](https://github.com/libmpack/libmpack-lua/blob/f3c8bf63c189a2ab114c099b5cc24e8083dc4f6a/lmpack.c#L37), unfortunatelly, it has some little flow:
Actually, `luaL_reg` was a part of 5.0 API (and not 5.1) which was deprecated since 5.1 (although, 5.1 had a kludge-`#define` for that, so it was hard to notice).
And as a side effect of that, current behaviour brakes the compatibility with modern releases of LuaJIT 2.1 (which [dropped](https://github.com/LuaJIT/LuaJIT/commit/dc320ca70f2c5bb3977b82853bcee6dad2523d01) 5.0 compatibility defines some time ago).

So, I see the fix in two variants:
[not as good as it can be] 1) detect that it is LuaJIT (even if 5.1 API is in use), and add that typedef in that case too;
[pretty good, imho] 2) fix code logic in a bit reverse way: use "modern" API (such as `luaL_Reg` instead of `luaL_reg`), and add `#ifndef` blocks with that API functions to define them (probably, even without taking `LUA_VERSION_NUM` into account).

How do you think?

**Comment by tarruda** [comment]
:+1:

Can you send a PR?
